#+TITLE: 2月12日 素材积累


* 疫情
** 摘抄
它一定不会想到，经由它制造出来的疫病、死亡、流言、信息，在它的饱和攻击之下，我们的日常生活一下子敞亮起来，有了灵性，有了一点神光，被重新发现，变成了造物者的无尽藏，这大概是出乎它意料之外的吧。

我们并不是一座空城。在街道后面，在立交桥后面，在二环三环的道路后面，是千百个社区，楼宇林立，灯火繁盛，并不比密云中的星辰、星座与星系少。每一个人，都因为这一场时疫，因为伤病者与逝者的馈赠，得以发现自己的城市，自己的社区，自己的家，以“武汉人”的名义，得到重生。

是的，武汉疫情需要关心，湖北人民需要牵挂，但这和怀念科比并不矛盾，且在本质上是一致的。无非都是对生命的悲悯，对人间的共情。

对涉疫情信息传播的处理宜应坚守法治轨道。这跟疫情防控目的也有相通之处，那就是保障人们的权利——不论是生命健康权还是正常表达权。如果有关方面执法过度，造成社会公众噤若寒蝉，甚至许多正常表达或有益信息也自动息声，反而会对防疫造成负面效应。

** 点评
注: 对美国投毒的传闻，我虽然也不同意是这样，但确实没有理论能反驳。
在非典的时候就有这种理论了，去搜索 [[https://en.wikipedia.org/wiki/SARS_conspiracy_theory][SARS Conspiracy Theory]] 就有，
论据也很充分，而且维基百科的资料应当是绝对真实的。
上面说的是，非典病毒只针对亚洲人的某种基因，
其它的人种对它有天生的抵抗力，死亡率非常低，基本上不怕被感染。
而且谁说美国就会保护美国人民了，911 事件都有过先例了。

但谁也没法从基因上证明。而且这么做也找不出什么理由(军事上的生物武器实验?)
我觉得除非有人能证明，不然还是不要天天因为自己的被害妄想症而担惊受怕了。

* 救黑熊重要吗
** 概括
1. 救黑熊与其它慈善事业等，都是重要的事。
2. 人最终做某件事只是偶然的动机，而不是选择的结果
3. 所以并不是所有人都选择最重要的事先做
4. 救黑熊本身是好的，无可谴责。

** 点评
我觉得关于要不要救黑熊，只是人自己的喜好罢了。
我们如果要谴责某个人，也只是因为他的所作所为不符合我们的喜好。

所以我觉得不管干什么事，都没有绝对的原因可以谴责，
我们帮助别人，也是因为自己能感受到快乐，或者对自己有各方面的影响，
或者是反面的动力，如果不帮助别人，自己就会过意不去。
而不帮助别人，就是觉得这事跟我没什么关系，我对它没什么感觉，懒得管。
人干的事一定跟自己有着各种联系，只是这些联系很多都难以发现。

人不是为了“黑熊的好”而救黑熊的，人是因为自己“想见到”黑熊的好，
而救黑熊的。所以慈善事业是值得提倡的，但它并没有什么特殊的崇高的动机。

就像有些人不觉得吃肉很残忍，但有些人只吃素，除了被迫的之外，
也许就是觉得吃肉太残忍，但是照这么说，植物也是生物，
吃植物是不是也太残忍？那么人是不是没法活了。

所以文章的主旨就一句话:“大家都不一样，只是我乐意这么干。”
