#+TITLE: 僕の日本語学びガイド、初心者へ 〜 给初学者的日语学习指南


* 始まり

首先，我要吐槽一下现在中国遍地都是日语的现象。

不过没关系的，我下面就要吐槽日本现在遍地都是英语的现象。
但是人家日本前几年还是很高级的，遍地都是中文:-D

好吧当我没说，现在日本也是遍地汉字。这真没办法，他们可以试试只用假名，
然后就可以无限玩谐音的梗了。

不过看到中文我们很亲切啊，看到一堆假名是最不爽的事了。

好吧这些后面再说，说回来我当时学日语，原因就两个:
看遍地的日语很不爽、看中文字幕或翻译很不爽，
并且重点在后面一个，所以我的目标就主要在阅读和听力上，
所以现在也完全不会口语或写作。所以我下面讲的可能会有些片面，
不太会关注想要学口语或写作的人。

另外，我是纯自学，网上的视频课什么的都没看过，就是先看看教材，
然后硬看原版书和番剧之类的，或者直接去逛日本的网站熟悉网络用语，
这样最快了，相信我。

好吧。反正第一步是有充足的动力和时间，然后买教材。
我买的是那本烂大街的「中日交流標準日本語」，
中级的两册带你领略一部长篇连载爱情故事(所以说日本的风格啊...
看个教材都猝不及防)。不扯淡了，我觉得这本书讲的实在有点烂，
语法点零零碎碎的。别的教材我没看过，不予评价，
但我强烈建议不要看这本教材入门，不然你的语法会一团混乱。
(注: 我刚看了看新编日语，感觉语法和其它好多细节，讲得都好很多，
但还是不尽人意，而且阅读量有点小。)

* スタート

我假设你现在刚拿到你的教材。

第一步永远是背五十音图。(不要看它叫五十音图，其实只有 46 个，
是不是顿觉轻松一些(滚))

我两天之内，抽自习课时间把平假名硬背下来了。首先，片假名可以先不背，
但平假名一定要背，不然没法学了。平假名看到字能较快地联想读音，
就差不多了，这真没那么难。

如果书上没有讲故事的话，我来解释一下日语里的汉字和假名分别是怎么回事。

在很久很久以前，日本的小岛上生活着一群无忧无虑的土著居民，
他们说着当地的方言，也没有文字。

然后有一天，来自一个遥远神秘的国度的航船驶来。
日本人突然发现，原来世界上有文字的存在。
于是他们给自己的每个词语，都根据意思配上了一个汉字，
于是说的话可以完美地转为汉字，只是中国人也看不懂罢了。
由于汉字实在太难学，古时候就连中国也多数是文盲，所以日本也差不多。

这种汉字在现在叫“训读”，就是写作汉字，但读日本的本地话，
汉字只用来表意，不用来表音。
一个字对应的其实是一个词语，一个完整的意思，所以通常不止一个音。
因为这些都是日本当地的日常用语，所以都是生活中简单的词语，

渐渐地，他们发现自己的词汇实在太贫乏了。
有许多在中国的留学生或官员，学了好多汉语，但找不到对应的日语词。
他们一怒之下，开始在日文中直接夹杂中文。好吧不是一怒之下，
应该是对中国怀着崇拜之心。就跟现在说中文的时候夹个英语一样，
其实本来是很不和谐的。总之这些词语写成汉字，
也读做汉语的音，反正就是跟汉语一模一样，硬生生塞到日语里面的。
最一开始传到日本的是吴音，这个在日语里占的比例挺高的，
所以日语听起来，有时候会很像吴地的方言(比如宁波话)，不是你听错了，
说的就是中文的方言。后来又传过去汉音、唐宋音，我也搞不懂是什么玩意，
反正就是总共三套读音的系统。所以你明白了什么呢？

日语现在的一个汉字可以有 4 种以上(训读可以不止一个)的读音。本地的“训读”，
还有直接把中文拿过去的统称为“音读”，放在不同的词里面，读作不同的音，
到底怎么读，要看这个词是什么时候传到日本去的。这种混乱程度可见一斑。
所以说，你要是背英语单词感觉很无厘头，感觉痛不欲生，
我觉得很正常，因为英语其实就是和日语一样的混合语言，
而且也许比日语还混乱一个等级。所以你一会儿在背英语本地的拼音，
一会儿在背法语，一会儿在背拉丁语，一会儿在背德语，
一会儿在背它们的词根混合拼在一起的单词......

所以不纯正的语言就是让人很头疼。
不是我说，我真的愿意在学英语之前，先去学学拉丁语好了。

方法论1: 日语里面，因为训读是简单的词，后来引进的音读是比较高端的词，
所以如果看到生字(当然对中文来说是已经认识的字:)，
大概可以用这个方法来猜它读的是什么。

我看的教材上关于这些啥都没写，所有的这些方法都是我自己总结的~~~

现在穿插假名的由来。

在训读和音读都已经传入日本之后，我也不知道是什么时间，
日本的民间老百姓也想学写字。可惜的是，汉字真的太难学。
真的学不来。于是人们想，我不一定要用汉字表意啊，
我能把我说话的读音记下来，就万事大吉了啊。我不如自己发明一套拼音。

我感觉他们真聪明。这岂不是可以用来默写作弊？

总之伟大的民间智慧就诞生出了一套拼音。
有平假名和片假名。它们出现也有先后，是互不相关的，你可以自己去网上查，
我不太了解。但要知道，假名自始至终是拼音。

后来经过历史的车轮碾压，平假名变成了“平”常用的假名
(这样记住怎么区分这两种假名了吧)，
片假名的地位跟英文中的大写字母一样了。
直到英语统治世界，片假名担负起了音译外来词的重任。

我讲的科学一点。平假名、片假名都是 46 个。
都有一张表，叫五十音图。你翻开教材，第一页肯定就是。
一列上是: a,i,u,e,o 五个韵母，一行上是: 无,k,s,t,n,h,m,y,r,w 等声母。
(我这是用中文拼音的方式讲。)表格对过去一个字一个读音。
有些字的读音有变化，请仔细看教材和听力内容。
其它的什么浊音(就是 k=>g,t=>d 这类)、长音，
还有四个迷你版假名 ゃ,ゅ,ょ,っ 见教材。

这就是所有你不认识的日文字了。就这么几个你还背不下来？
就把这两张表背完，你就可以装作自己懂日语了(至少所有的字都认识了:)。

现在先不管片假名。日语里那些不认识的字几乎都是平假名。
你会发现它们是汉字的草书演变过来的，笔画都很简单(适合作弊)。
既然官方都采用汉字，只有民间用假名，那为什么后来它们混合起来了呢？
简单。因为大家都发现了对方的优点。汉语很高雅，但难懂，
而且也不能很完美地跟日语对上；假名好学，好写，专门表音，
但一长串写起来就像被加密过一样(还真可以当密文)。

方法论2: 所以现在大家都比较随和了，但较偏向于假名。
日语现在属于表音文字。所有的汉字都可以写成假名(不管是训读还是音读)，
但有些日语本地的词语没有对应的汉字，只能用假名写。
汉字纯粹是为了让文章表意更清晰的存在。
因此，就算你的目的只是看书，也一定要记汉字的读音，
因为说不定这本书的作者喜欢用汉字，那本书的作者就喜欢用假名。

方法论3: 反之同理。你也许一直只记某个词的假名，
然后看见别的书上用汉字，你就不认识了。
所以每个词，特别是教材上只告诉你假名的词，都一定要到字典上去查。
从背第一个词开始就要学会用字典。

举几个例子。(现在我的教材不再身边，希望我没记错。)

第一篇课文，大概会讲 你我他 这些人称和一些简单名词。
比如，“我”，「わたし」，我的教材上只给了这样一个平假名。
但你去字典上查，就会查出来它其实有个汉字「私」，
就是说「わたし」和「私」是完全等价的，你爱用哪个用哪个，
现在书上用「私」的好像稍微多一点。

还有很重要的事。字典上会告诉你它是训读，也就是日语的本地读法。
然后你用笔画检字法查到「私」这个字，它还有一个音读是「し」，
(现在字典也不在身边，不记得还有没有其它音读了)，
然后还有其它的训读，比如「わたくし」「あたし」。
训读每个字都有明确的意思，但音读一般需要组词。
你如果以后看到「私」和其它的汉字组词，一般都是音读，
甚至「私的(してき)」这种词，初学的时候可能会认为用训读，
其实两个字也都是音读(这词现在先不用记，我就举个例子而已)。

再举个例子。比如「学生(がくせい)」，你可能一点也听不出音读的样子，
但它是音读。这样查了字典有什么好处呢？你以后见到「学」，
就知道它的音读是「がく」，见到「生」，就知道它的音读是「せい」。
你已经记了两个字的音读了。

当然补充一下，也别高兴太早，因为「生」还有其它的音读，
比如「一生(いっしょう)」里面「生」读作「しょう」。

教材里还有很多本来是音读，但只告诉你假名的。
比如「達(たち)」，表示复数的那个词，我的教材就是一直写平假名，
我一直不知道原来它是音读，一直不知道原来「友達(ともたち)」的「達」
就是这个词。

上面的这些情况，在我这本教材里出现极其频繁。
我不知道别的教材怎么样，词汇表里会不会写出这些，
写出来最好，不然我就建议勤查字典。学起来会事半功倍的。
我在看了上册之后，才意识到了这一点，赶紧买了本字典来。

在学了一定程度以后，就可以看字典上的例句了，比教材里的例句靠谱得多。
怎么查字典之后就不讲了。

好了，现在再回到读音上，我知道你一定想问，
为什么一个字的音读可能是两个音。你见识一下日式英语，你会大开眼界的。

举个例子。英语里进行时的“ing”这个词尾，你猜日语怎么音译的？

答案是「イング(いんぐ)」。看出来了吗，“g”这个音居然被音译进去了...
再看一下“L”这个字母的发音，它音译为「エル(える)」。
好了你该明白了，你可以先自己震撼一会儿...
还有，要学日语的话，日式英语是一定要学的，原因嘛...
我还是后面再吐槽吧...

所以我推理一下，可能传到日本的那些中文方言的注音，
就有一些这种词尾的音。它们本身并不发音，
但是日本人直接硬生生地把它们译进去了。
所以好多音读后面都带着「く、ち、つ、き」这些音
(这时都类似于中文的轻声)，特别是「つ」这个音，跟促音「っ」有密切联系，
我怀疑日本人就是把中文里，类似促音的这些音直接读出来了...

当然这只是我自己的猜测，但我觉得可信度比较高。
只是这个结论让我有些无语~~

不知道还有没有读音上的问题，我会补充在这里。
下面自己读教材应该就没太大问题了。

* コンティニュー

我上面一直在讲单词的由来，但是需要重点提醒的是，不管学什么语言，

方法论4: 掌握语法最重要！单词永远让位给语法。

方法论5: 语法不要死记硬背，要读出语感。特别是日语这种，
能读出很强的语感的语言，也就是语法有点混乱的语言。

我的建议，也是我初学时的做法是，我先按顺序看了看前两三课，
把最最基本的单词背一背，然后不管单词，直接往后翻，
课文看不懂就硬读，单词不认识的实在太多就翻词汇表。

重点是先看每一课的语法讲解。教材里所有汉字都附着注音，
所以可以读得很流畅，即使你一个字都不认识。
先做到能看懂语法讲解中，每个句子的语法结构。

接着举例子，比如第一课，肯定就是个判断句式
#+BEGIN_QUOTE
... は ... です
#+END_QUOTE
(这里的省略号一般读作「何(なに)」或者「何何(なになに)」)

但是我看到后面的语法之后，知道了，原来这是敬体的形式，
至于为什么上来要先教敬语，我不知道(别的教材也是这样的吗？)，
但我知道我主要想学的肯定是简体，因为番剧里说话简体居多，
小孩从小学说话，学的肯定也是简体。敬体只不过是简体的一种变形罢了。

所以，对着第20多课讲的简体形式，直接把课文转简体。
#+BEGIN_QUOTE
... は ... だ ，其中「だ」可以省略
#+END_QUOTE
因此，\\
方法论6: 把语法全部翻遍以后，根据自己的需求灵活变通。

然后我发现，这句式很像文言文诶。
#+BEGIN_QUOTE
... 者 ... 也
#+END_QUOTE
这个“也”字表达的是一种强烈的判断语气，省略“也”字，就是比较普通的陈述句。
类比一下日语，是一样的。

名字的语法简单，主要是后面讲到动词的时候，我的教材居然自己发明术语，
而且在词汇表里给的是动词的「連用形」，就是跟着「ます」的形式，
不给动词原型。要是我没有先把语法浏览一遍，直接跟着背，
背到后面发现，什么？我背的一直是动词的敬语的变形？
你还跟我讲动词的其它变形？然后告诉我动词的简体形？我估计要疯了。
我不知道为什么很多人说这本教材好。

所以我一开始背的就是动词原型，对话都自己翻译成简体。
我一开始就自己总结了类似这样的东西:
#+BEGIN_QUOTE
动词原型: ある    否定: ない
敬体: あります    敬体否定: ありません

表判断: だ    否定: ではない
敬体: です    敬体否定: ではありません
#+END_QUOTE
所以你看的出来它们之间的关联。你就知道表示否定判断的
「ではありません」是怎么来的了。「で」有一种“这种情况”的语感，
和「は」连起来有一种“这样的话，...”的语感，
而「ありません」就是「ない」的敬体，「ある」有一种“存在”的语感，
「ない」有一种“不存在”的语感。连起来就是“这是不存在的”:p

接着举例子。其实都是一样的，就是让你们更好理解一些。

比如一些寒暄语，如「こんにちは」，它其实是「今日は」，两个字为音读。
「すみません」就是「すまない」的敬体，是「済む」的否定形式，
而「済む」是轻微的意思。

当时这些单词我还没背，我就能一眼看出来它是什么变形而来的。
我读课文的时候，读一遍书上的敬体形式，然后自己读一遍简体形式，
或者自己把各种变形都用上去。

除了动词变形最疯狂以外，形容词、形容动词和副词之间的变形，
还有各种形式的对句子的词性变化(其实就是类似英语里的从句)，
这些主要是靠那几个魔幻的助词。

把书里所有语法都过了一遍之后，你的内功就足够深厚了，
然后再把书再翻回第一篇课文，开始重读课文和背单词的旅程。

* アゲイン





# 背日语单词，需要学好英语
# 文言文单词