#+TITLE: 再忆往事


我自己写的东西都不免有美化自己的成分，一直是像一个明白人一样，
不外乎是批判什么，宣传什么，讲什么故事，诸如此类。
折腾地多了，我又开始怀疑自己，我这么做到底有什么用处，
我是为了改变社会吗，还是为了我自己？我信不过书上的和别人说的东西，
因此我一直在自己想着各种事情，结果觉得自己好厉害。
过了段时间再看看，自己就是纯属为了写文章而写文章，
觉得自己好蠢，又有损自己的形象，就又一篇一篇地删掉。这种事情干过不少了。

但我仍然在写，我希望有一天我能知道我在干什么，能写出更真实的东西。
我似乎发现了，如果文章写得好，通常就太过理性了，
如果想要写得真实，最后就会不知道自己在写什么。
我以前觉得，好多东西说出去，别人都理解不了。
我觉得别人都只关心我表现出来了什么，并不会去理解我心里想的是什么，
别人会拿评价一个人的表现的态度去评价我心里想的东西，我害怕这样。

后来我才意识到，我并不是什么特殊的存在。
如果我在说别人如何，我多半也是在说自己，我也能从自己身上找到答案。
所以我今天就写了这些。这不是篇文章，只是个烂掉的草稿，
我想到哪里写到哪里，没有任何可读性，有很多随口带过的复杂的事，
也有很多被我忘记很久的细枝末节。不过也许你会知道我在说什么吧。

-----

有可能从小开始，我在潜意识里就觉得自己很弱小，我很害怕别人会发现这一点。
我很胆小。我不觉得胆小有任何不妥，因为别人会把它称为文静、谦虚。
我回忆不起来，小学的时候我是否真的是谦虚的人，
但反正那时候，还有爸妈天天保护着我。
我觉得自己还很小，我能找到足够强大的人作为依靠。
初中住校之后，我仍然害怕自己面对未知，我觉得自己还没有这样的能力。
我会想家。要是遇到了什么困难，只要钻进家门，我就能完全地逃避了，
我就有可以依赖的人了。但之后我渐渐地意识到，
我不可能再找到谁可以依赖了。我开始觉得教室是不安全的地方，
我开始在晚自习时，一人跑到黑夜里闲逛，在校园没灯的地方想着心事。
这个习惯就这样从初一持续到了现在，我未曾成功改掉过。
# 即使一片漆黑非常让我恐惧，那里还是有东西在吸引我，让我小心翼翼地走进去

我心里仍然很空虚，我仍然觉得害怕。我觉得我只有自己变强才行。
我要怎么办呢。我不知道怎么样算是强大，但我知道我不想再这样弱下去。
我开始在学校疯狂地做题。我不敢给自己闲下来的时间，
让心里的这种自卑感浮现出来。我似乎找到生活的意义了。
不停地给自己找事做，这应该是很自然的事吧。这样我就安心了。

我可能真的变强了。然而我发现世态变了。别人仍然拿那样的眼光看着我。
我在初中居然就像一个整天闷头读书的书呆子，似乎没人意识到我的存在。
我发现我受到了挑战，我发现别人只要马上就能看见的成绩，
只会记住我马上就显示出来的错误。我居然混不进班级里了。
我想起来小学的时候，就有时被同学起哄或者嘲笑，
我觉得别人也许不是恶意的，但我自己只能憋着委屈，回到家去发泄。
有几次我挥拳打了过去，却一点也不疼，被以为是在闹着玩。
我受够了，我要让别人知道，我不是因为只会学习就能随便欺负的人。
我害怕别人发现我的弱小，就只能让别人都承认我是最强的。
就这样，我创造出了装逼协会。我再次安心了。

只不过我偶尔还是会梦到这些我害怕的事，我一个人在墙根走着，
却一路听到前方传来的闲言碎语。有些场景给我留下的印象，
让我搞不清楚我是否真的经历过这些事了。我难以理解。
因为我是一直都不在乎这些的人啊。我从来都不是那么关心我的成绩的，
也很少为成绩开心或伤心过，况且我很清楚自己的能力，
我也不想给别人评价我的机会。当我最终发现，原来似乎看不起我的人，
现在都在称赞我时，我一点也不高兴，我难受极了。

没想到后面还有更大的威胁。我永远也忘不了那一天。
要进行班级布置了，一天中午，下课后我还在教室里，
这时两张纸板被抱了进来:“信游大，得永生”。我的班主任姓游。
我当然知道这是开玩笑而已，但我没法平静下来。
如果，游老师有过跟我一样的经历，他会不会也为此感到痛苦呢？

我知道，只要有崇拜的对象，别人就会形成自己的团体。这就是对我最大的威胁。
如果有人批评我，嘲笑我，那不可能是他自己一人。
我爸妈可以骂我，是因为有家庭，
老师可以随便让我罚抄，是因为有学校，
同学可以欺负我，是因为他们身边有一帮朋友。
我恨别人的团体，和那些喜欢助长这些团体的人。
但我又怕他们，我觉得我背后肯定没人会给我撑腰。
折中的结果就是那一篇贴在墙上的文章。

第二天，我盯着班主任一路走到那块标语前，他伫立了很久。
随即他转过身来，面无表情地说，“下课就摘掉吧。”
我心里不知为什么闪过一阵对他的同情。不知道他那时是什么心情呢。

不过这下终于没人来挑战我了。看来写文章是个好东西。

我又喜欢上了写文章。我正好有一肚子的憋屈，我疯狂地写各种事情，
就像我之前疯狂地做题一样。
也许还有人记得高一时，我一篇篇地把这些东西发到网上。
我顺便可以让别人觉得我不只是成绩好，我还很有自己的个性。
我也不知道我在写什么，只是只要我把其它所有的东西都批判一遍，
我就满足了，因为这样就没有别的东西比我强了。

经历了这么多，其实我只是跟小时候一样，
害怕被别人发现，我因为心里其实承受不了任何的打击，
所以我才会骗自己，以为我自己对这些都漠不关心的样子。

我并没有一个目标，我只是在试图逃开自己心里所想的东西，
这样我也许能创造出另一个别人眼里的自我，也许他对某些东西很热心，
也许他会很高冷，不管是什么样的，我会把他当成我自己。
这个自己就不用再面临心里的自卑了。

跟以前相比，我似乎变了很多，我经历了大大小小的事情。
可对我来说，什么都是一样的，我不过是为了建立在别人面前的形象，
只是想得到别人的认可罢了。

这么活着太累了。每过一段时间，我就反复地指责自己过去的事。
我隐约地感觉到了，我心里的一些冲动也许不可能再压抑很久，
我预感到我也许会失败。慢慢地我再次变得越来越害怕，
我不知道该做什么好，我不会面对其他人了，
我不知道还有什么是我能找到乐趣的东西。
每天在校园里闲逛消磨时间，晚上还是躲在没灯的地方胡思乱想，
看着眼前黑洞似的景色。我不知道自己身上发生了什么。
我似乎并没有做错什么，也没有遭受什么挫折，
我不知道我怎么会感觉完全地心灰意冷。
我想，也许这是世界的错，我在这个世界上没法追求我想要的东西。
我有时候会整天整天地思考世界上的各种问题，我以为没有人能理解我了。
有一天我想，我应该下定决心，我要去实现我自己的梦想，
我想，我要鼓起勇气，我以为我可以像电影里的主角那样。

结果这时我真正地慌了。
我发现我不知道我想要什么，我没有自己想要追求的东西。
我发现我只是过着平淡无奇的生活。这样的生活跟坐在教室里，
整天不知为何而努力学习的状态也没什么不同。

我怀疑难道是我太中二了，以为自己经历了什么惊天动地的大事？
什么都没有，也许就是因为我的生活太正常了，所以我想随便找些别的事情？
似乎是这样的，但是我到底想做什么呢……

我坚持不下去了。我从未想到过原来我这么不了解自己，
我以为跟着我的思想走，我最终就能找到我的目标。
我发现我原来并没有方向，我似乎被我的思维拖了很远，而不知道自己身在何处。
我也许不应该再找到什么地方躲避了，
我也已经绝望了，我没有任何的去处，没有想做的事，我的头脑是一片灰暗的。
我再思考也不能带我去任何的地方了。我真的失败了。
我不知道我失败了什么，只是隐约觉得是我一直挣扎努力的东西，
而我现在无力抵抗它们了，或者说放弃了。

我渐渐地回想起来了许多被我忘记的事。当我放弃的时候，
这些东西就自然而然地冒了出来。那些后悔的事情，我以为已经忘得一干二净了。
我以为过去的事都只是负担而已，我一直想改变未来。
然而之前我对自己所有的指责都从我的记忆里跳了出来。
原来有过这么多次，原来我的理性始终是失败的，我靠着努力无法改变未来，
我只是一直在换着花样重复相同的事。我意识到自己是如此的分裂，
我是我的思维创造出来的形象，这个形象似乎有自己的愿望和生存方式，
我无法感受到我心里究竟是什么想法。也就是说，我不是一个完整的人，
我在抵抗自己的另一部分，我心底更真实的一部分。

我不敢相信我心里流露出的这些，如果我接受了这些，那我会变成其他的人吗。
我的心里对我来说似乎是未知的，我没有尝试过去理解它。
好像不是这样的，是我害怕去理解它，因为我害怕心里的自卑感，
我害怕会失去我一直以来努力的结果。

我突然明白了，一直以来，我只是害怕别人的一句批评，
我想在别人面前显得不是那么的脆弱。我始终无法接受自己的脆弱。
我渴望能让别人承认自己，这样就表明我已经不是那么弱小了，
并且我信以为真了，我会表现自己是最强的，我不需要心里真实的感觉。
这就是我这几年经历的一切。

我只能在这里苦笑，我这么久没有明白什么人生的真理，只是发现自己转了一圈，
又回到了好多年前而已。我不知道接下来该怎么做，
不过我现在多了个选择，我会尽我所能问问自己的感觉。
因此我也把我写的这些东西发出来了，因为我希望会有人理解的。
就这一点上，我还是本性难改啊。
最后，如果说我有什么新年愿望，那就是我想找到自己的愿望，
我会尽可能改变现在的生活。我不知道我会不会有这样的决心，
只是希望它不会因为我说出来而不灵了吧。