#+TITLE: 被逼出来的一篇语文作文


* 关于英雄的一些思考

说到英雄，我们心里想到的都是为国家或他人献身，
然后被宣传，被大家瞻仰的人。

为什么那些英雄要为他人付出，甚至许多时候牺牲自己呢？

我认为这里有赌博的成分。他们肯定不是单纯想成为英雄，
也不只是愿意为他人牺牲。
英雄很大程度上是为了自己，保护自己珍重的东西: 自己爱的人、
自己所属的团体(国家、地球...)，或者只是觉得，
如果自己不努力一把，最后的结果只能更糟糕。

所以他们就变成了英雄，不管最后结果如何，
如果是大家一起死，那也没区别，如果是把大家一起救了，那是皆大欢喜。

最糟糕的就是，把其他人都救了，自己承担了一切灾难。
他们就只能活在史书里了。

到底有多少英雄是自愿牺牲的呢？反正大多数肯定是觉得，
等死，死国可乎，不如赌一赌，说不定赢了呢。

最后要是输了，就当成是换个后世的荣誉了。心里多少是遗憾的。

在远古时代，每个人都独自生活的时候，应该是没有英雄的。
有了人类的聚落团体，大家有了共同的信仰，人们渐渐地认为，
团体的幸福就是个人的幸福，甚至认为造福人类可以在死后得到更大的幸福。
于是有了主动为团体牺牲的人。另外，人们过分看重英雄的荣誉，
为了荣誉，牺牲自己也没关系。这样又诞生了许多的英雄。

所以许多英雄要么是为了实实在在的利益，要么是为了虚幻的利益。

但是人也不一定完全为了自己。也许确实有一些英雄，
更大程度上是为了他人，从而牺牲自己。
他们的理由似乎很单纯，只是为了实现自己的价值，
觉得为他人服务是自己应该做的。帮助的全是陌生人，自己一点好处也得不到。

这才是反常的地方。也许是我的精神境界不够高，
就算是帮助他人，也至少是因为自己觉得不爽:
别人有困难解决不了，我看不下去了，帮他一下，耳根清净。

或者给别人捐款: 大家都捐啊，那我也捐吧。

觉得自己道德高尚只是些精神安慰。

我们真的会单纯地为了他人而奉献自己吗？

#+BEGIN_QUOTE

(这段话是我之前在网上写编程随笔的时候，不知道怎么就写到这里了，
复制在这里。)

有时候我会梦想，希望人类能像三体人那样有透明的思维，
这样世界上就不会有语言存在了，大家都能互相理解了，
真是个美好的世界。(另: 作为学过 程序+语言 的人，
我能看出《三体》的无数 bug...而且我一点也不喜欢这本书，
所以我喜欢拿这本书举例子)

不过同时，你会发现个人不存在什么自由了。为什么呢，
比如世界要毁灭了，需要牺牲你才可以拯救(这是什么中二情节)。
你当然怕死，但是其它所有人的痛苦你都能感同身受，
我认为，在这种情况下，你一定是很直接地选择自愿去死，
而且并不会像地球人拍的电影里那样各种纠结、遗憾。

这其实等于你的思维、情感，已经是整个人类的一部分，
你是没有什么自我意识的，整个人类已经组成了一个超级大脑，
他们会诞生出一个真正的集体意识。你以为是你做出的决定，
其实是这个集体意识做出的决定。为了集体可以牺牲部分。
你具有的自我意识可能只是一种错觉。

(对于看过 Eva 的人，这就是那里面所说的人类补完计划。)

但人类有语言这个屏障，人是不可能理解他人的，
人能不能理解自己都是个问题。这就是我这么希望研究语言的原因，
自然语言，还有程序语言，音乐、美术的语言，甚至是电脑游戏。
我想找到那些能表达自己的东西，能在人之间建立起联系的东西。

所以在这一系列教程的前言里，我最开头就放上了巴别塔的故事。
就这么一点传说，当时却给了我很大的触动。

但是问题也在于，这样世界真的会向美好的方向发展吗？
现在信息技术发达多了，可以说，人类之间应该是联系更紧密了，
所以人类应该更加互相理解了。

我认为是这样的，人们更能互相理解了，至少沟通的手段多了。
但是这跟人的幸福似乎是相反的，似乎人之间的联系能够增加多少，
人类这个集体的意识也会相应增加，人似乎就更听从于集体的决定，
承担为了集体而给自己带来的痛苦。

你可以类比一下，你身上的每个细胞都像是一个独立的人，
但是为了你的生存，它们不停的工作，甚至有的已经变异得认不出来了，
就为了能让集体生存，要是这个集体死了，它们都会死。
它们只能听从这个集体的意识，即使这会给它们带来痛苦。

所以我们是不是应该对组成自己身体的任何一部分，稍微多关爱尊重一些？

我不确定细胞也会有痛苦，至少它们的意识是跟我们完全不同的存在。
但是可以猜想，如果人类这样发展下去，也许也会成为这样的一个整体，
我们会诞生出整体的意识，人类在其中会失去自己，或者被免疫系统自动清理掉。

如果想保持个人的自由与幸福，我认为发展应该是有限度的，
人类之间的联系增加，人类整体的发展，都是以牺牲个人为代价的。

但换个角度说，这也许又是人类进化的终极途径。试想一下，
如果整个地球诞生出一个整体的意识，我们是它的细胞，
这会是什么样子，我是无法想象的。

也许我臆想的成分实在太多，但是不管怎么说，我始终都在矛盾之中。
我觉得世界上的痛苦都是人际关系导致的，我指的不是简单的与人交往，
而是所有人之间，有意无意的互相影响。如果从古至今只有我一个人的存在，
我就不需要面对所有的这些问题。

所以最一开始，单细胞生物诞生的时候，为什么它们要想到组合在一起，
甘愿成为高级生命的一部分呢？为什么要牺牲自己来创造更高级的生命呢？
世界上就自己一个细胞，快快乐乐地生存不好吗？

还是说，真的还是有什么自然规律在支配这些吗？

但是现在既然有这些问题了，交流似乎就是唯一解决问题的途径，
交流都是通过各种形式的语言来完成。所以研究语言，
似乎就可以解决我们所有的烦恼了。

问题就是，这个解决的结果，到底是人类快乐地共同生活，
还是人类已经不作为一个个体存在？

也许两者都是，也无所谓快乐不快乐？

是的，我研究的是程序语言，而且研究地挺深了，我也喜欢接触其它各种语言，
比如日语，见[[./japanese-learning.html][此链接]]。但在这期间，我也想了很多很多，
我不知道这样的研究，和人类的发展，究竟会带来什么。
我自己当然没有这么强的能力，让人类之间的联系获得巨大的进步，
但是这样发展下去，总有一天会有这样的结果。
人类以前认为发展是好的，现在认为在环保的前提下，发展是好的，
有多少人明白发展到最后，到底会带来什么东西呢。
在这之前，我们就一直这样研究下去吗。
#+END_QUOTE

我认为真正的英雄是人类社会发展的产物。信息技术越发达，英雄就会越多。
因为主导英雄的可能不是他们自己，而是整个人类产生的神秘的力量。
这么说可能很残忍，不过也许所谓的各种道德精神都是这么回事。

所以英雄就是找到了人类进化方向的人，
或者说，认为未来的方向比现在更重要的人。

所以也许我们需要英雄，也许我们都可以成为英雄，
但不管英雄的定义是广义的还是狭义的，英雄的出现未必是件好事，
每个人都是英雄也许是最差的结果。