#+TITLE: 论人的理性


我其实不想写这种东西，因为我很讨厌哲学家那种在文字上绕来绕去的风格。
但现在写的是对我来说最重要的东西，我想过很久，都不知道如何下笔。
如果你理解不了我下面写的东西，你就把我当成是疯了好了。
民科在此。

* 我观察到的人

我要说的东西可能会很奇怪，也许你们以前没有想过这个问题。
我先编几个例子来说明一下。

比如我在看一本书，这本书非常有趣，我感到很开心。

我的问题是，我为什么会感到开心。

答案可能是，因为这本书非常有趣。但还有很多种可能。
比如我正在旅游的路上，所以我很开心。
或者我可能刚好听到了什么开心的事，潜意识里我很开心。
或者我在和很多朋友一起读这本书，他们都很开心地笑了起来，
于是我也不知道为什么跟着感到很开心。
或者夸张一点，我刚吸了毒，我不管看到什么都很开心...

也许你还是不明白我想表达什么。那么，如果那本书其实很无聊呢？
我只要在上述情况之下，我依然会觉得开心。我开心不一定因为正在读那本书。
但是我并没有意识到这一点，因为我当前只是在读书，没干别的事，
所以我错误地认为，开心是这本书导致的。

然后有一天，我可能就会跟你推荐说，这本书很有趣...
其实我也不知道它到底哪里有趣了。但是之后再看到这本书，
我可能会回想起当时开心的经历，然后仍然觉得它很有趣。
这叫做如何错误地骗过自己。

再举一个例子。比如某天有人骂了我，然后我生气了。

我生不生气是取决于自己的。如果我一点也不在乎这件事，
我是不会生气的。比如我是个演员正在拍电影，我知道别人不是真的在骂我，
所以我就算要演出生气的样子，心里也一点都不会生气。

如果我只是不想挨骂，那我完全可以好好讲道理。
我生气的原因其实在于，这样可以让我占到上风，别人以后也不敢这样对我了。
所以，自己怎么做其实不在于别人，而在于自己的目的。
我做某件事，是因为想得到这件事带来的结果，
我不做某件事，是因为害怕这件事带来的结果。
但我们依然会说，是某事让我高兴、让我难过、让我生气...
这样就可以继续把自己的责任推给别人。

不知道我有没有说清楚。

* 回答一个哲学问题

也许我上面说的你早就知道了，但我有一天真的发现这件事的时候，
我当时是无法接受的。我感觉我被一个从来没有怀疑过的人骗了，
这种感觉不知道该怎么说。我之前从来没有想到过自己也许是不可信的。

如果要举例子还有很多，但是让我回忆到最开始，
是有一天我产生了一种奇怪的感觉。我那段时间在成天地发呆。
其实一直发呆是一件很累的事情，想得太多了反而想不动了，
会忍不住想要干点什么别的事，但我硬是坐着什么也不干，
什么也不想，慢慢地我发现了一些十分陌生的东西。
怎么说呢，我意识到人好像不是那么一个完整的东西，
人其实无法完全了解自己。我发现对自己跟对其他人是一样的，
我只能靠观察别人做什么、说什么来猜别人心里的想法，
如果我有一天说别人骗了我，也许别人不是存心的，而只是我猜错了。

我跟其他人说上面这段话的时候，他们好像无法理解我在说什么。
好在我后来碰巧看了几本书，我觉得也许用科学的方式更好理解，
大概意思就是，你看到的听到的其实不一定是真实的东西，
有各种实验证明了，其实你的思维会给它们加上一层滤镜。
这些实验其实都是废话。但是如果有人告诉你，
人的记忆、感情也不一定是真实的东西，应该也不难理解吧，
至少小时候在小说里也看到过，比如某反派被主角打败之后，
突然明白了原来自己一直在骗自己，为自己找一个光明正大的理由干坏事。

那该怎么办呢，什么都不信还有没有办法活了。
于是哲学家说，要相信自己的理性，只有逻辑推出来的才是真理。
如果我对哲学的理解有误，那我要道歉。但是我一点也不喜欢这类哲学家，
因为我觉得他们的路刚好走反了。他们不知道为什么其它的东西都不可信。
但是你可能已经看出来了，原因就是人的理性，
也许理性是人唯一过于相信的东西。

这又该怎么说呢。本来理性只是人的一小部分，但是我们把它当成是全部了。
我们总是认为，如果什么也不想，可能连自己是不是活着都不知道，
说话、回忆、逻辑推理都无从下手，所以我们觉得这是人独一无二的本领。
但是人们似乎过于重视这些理性的东西，人们现在不知道怎么摆脱理性了，
一切都靠思维去理解，然后思维反客为主了。

* 意识和思维

再说一下意识的这个问题。我不知道意识是怎么来的，
但是如果什么都不想，意识却还在，我还有知觉，还能感觉到自己活着。
我不靠思维就可以知道自己活着，只靠一点机械性的记忆就可以做很多事，
人会进化出比较高级的理智，只不过是为了把它作为一个工具，
让自己活得更好一点、更明白一点。没想到的是人们为它走火入魔了，
以至于宁愿放弃自己原本的意识。从这点上来讲，人还远远没有其它的动物清醒。
其它的动物也许只是不会想很复杂的事情，但我可以肯定它们会有自己的意识。

其实争论某个东西的意识没什么意义，至少对我来说，
要一直保持清醒的意识是很困难的，比如沉迷于做某件事的时候，
或者专心地思考的时候，我认为我是被思维控制的，
我这时其实处于一个意识很微弱的状态，我不知道能不能算是有意识。
相反，其它的许多动物，如果我的观察没错，倒是很少陷入沉思，
而是一直保持着一种意识清醒的状态。

我猜测有些人会不知道我说的意识是什么。你可以尝试一下观察自己思考，
把自己跟思维分开。我就是在发呆的时候，很偶然地感觉到了这些，
我发现这很奇怪，我好像不是一个整体，而是跟其它的部分有什么隔着。
然后我明白了，那就是我的思维。我第一次开始怀疑思维到底是干什么的。
我被震惊了。我在白天从来没有比做梦的时候想的少，
有那么多乱七八糟的想法从脑海里闪过，但我都没有注意过，
我认为它们是不该出现的想法，然后它们就被我压了回去。
在这之前我居然从来没有发现过，我心里出现的感觉和想法根本不是真实的，
而是由我的思维制造出来的。不应该出现的都会被它挡下来，
然后编出一个正确的逻辑来骗自己。

我仍然无法理解为什么人会变成这样。这不是如何思考就能解决的问题。
每次说到理性这个词，就会说到思考，现在有谁能确定思考就是理性的？
如果想要理性，我认为人完全没有思维的时候是理性的，
比如晕倒的时候，可惜这时人什么也做不了。
如果能完全意识到思维在做什么，应该也是理性的，
但我又不知道有没有人能做到。这里我没有对理性褒或贬的意思，
但是我想说的是，人们其实不知道什么是理性，
同理也不知道什么是感性，或者其它的很多东西，
这些词语都是从思维里诞生出来的，人们并没有真正体会过。

人就因为逻辑思维创造了一切的科学，就遍地推广逻辑思维的能力。
我想人进化出这么强的逻辑思维，已经在科学上有用武之地了，
如果要拿来研究自己，还真不是什么靠谱的东西。
你一定有过这种情况，做一道数学题，某个地方逻辑错了，但就是发现不了。
你会觉得这只是因为自己不够仔细吗？还是因为逻辑本身就不靠谱呢？
就算逻辑能轻易地造出各种悖论，人们还是觉得它是很正确的东西。

正不正确全在你信不信而已。下次数学题粗心做错了，
不要责怪自己不仔细，要问问自己的思维，“为什么你要让我相信我是对的？
你明明知道这里我在瞎写，为什么不告诉我？”

不只是逻辑，任何一种思维模式的不足之处，都是源自思维本身，
是人没能把握住全部的事实，然后让思维钻了空。
我说的事实包括外部的不愿意接受的事情，或自己心里不愿意承认的想法。
思维是个很好的工具，你如果真心地想要什么，思维就会尽可能地帮助你。
而且它太巧妙了，知道如何从各种矛盾中做出最好的选择。
人们什么时候才能学会好好对待它呢。