#+TITLE: 记我的逃学经历

我过年也很少熬到如此之晚，今天我只是在仓促地讲我的故事。

我当时躲起来的时候，根本没有做被抓回来的打算，虽然我现在还是坐在电脑面前打字，我已经说过好多次“这是我写的最后一篇文章”，可是前前后后电脑上就有20多篇，都是好几千或上万字的，只是都没发出来而已，因为我单纯不想让别人对我有这样的印象。哪怕让别人以为我是沉迷于电脑也好，以为我沉迷于弹吉他也好，高中三年就能这么混过去了。我现在也是这么想的。我被抓回来以后听了多少说教，说老师同学都找你很辛苦。我不觉得有多少人会找我很辛苦，都是在看热闹，反正知道我迟早要被抓到的。结果是合你们的心意了。如果有下次，就让我成为第一个再也捉不到的人。这次是我的失误。

我本来以为什么事都不会发生，那是很正常的一个晚上，教室不是适合我待着的地方，于是我走。然后我就听说我被找了整整一晚上。虽然除了两个同学，我连人影都没看见过。所以我回到寝室的时候就傻了，我先看到班主任怒气冲冲地对着我，然后看到我妈也在，她从公司一晚上跑到学校的速度怕不是坐了赛车。算了，再忍一次，然后把他们赶走，自己好好睡觉。我已经腻了，第二天早晨起床的时候，我心里想的是，直接找去办公室，他爱开处分就赶紧开，懒得开就不理他，然后就什么事也没有，紧接着期中考。没预料的是，我甚至还没有叠被子，我妈冲了进来。第一句话是一个劲地催我吃早饭。我继续叠我的被子。她一把拉住我要谈心。我刷我的牙。她一路追过来要和我谈心。学校已经无处可去了，原来现在我连家里也没法回了，我毫不犹豫地选择走。现在我把自己关在屋里，没有谈心了，不然我还会毫不犹豫就走。直到晚上10点多，我没有水，没吃过饭，快被冻死了，虽然也无所谓，但总要先去把我的日记和隐私销毁了，顺便还能偷瓶水，我就是这么想的。于是我也无法理解，我在全黑的山里，从我爸身边走过，硬是没看见他。如果是平时，我也能再次跑掉，这次力不从心了。

我一开始就没有做被抓到的准备。我学会了跑到永远不会有人的地方。我会跑到梓荫山的树林里，我学会了爬树，翻寺庙的墙，手脚并用爬上那个接近垂直的山坡，以前我以为真的会摔死很多次的事情。还不够，我被逼得翻到女生寝室的墙根，然后翻到体艺馆二楼，从桌椅下面爬过，然后一路贴地爬到音乐教室，起身时我身上的灰差不多可以让别人认不出来了。之后走遍了电教楼，从校史馆中间的侧门出去，再跳窗，上报告厅，再从厕所边的楼梯上图书馆，然后进剑桥楼，再从食堂边上溜出来。然后返回体艺馆，然后翻上梓荫山。学校的猫能到的地方我都见识过了。晚上的时候，我就坐在女生寝室门口的树丛里，五六只猫就围在我身边。唯一没有老师经过的地方。那些猫也不把我当生人，在我面前不停地转悠。我去梓荫山的时候，总会随身带着几页猫语辞典。于是我明白它们都很饿，想知道我在这里干什么，小猫还都想挤到大猫身边去。我已经在浑身颤抖，真希望有哪只猫能帮我取取暖，但是辞典上没有这个词条。再过了很久，居然有老师真的找到这里来了，于是我又逃到体艺馆。

我从来没有想到，这个世界上，竟然让人连躲都无处可躲。

我有地方可以翻墙出校。在书吧的后面，爬上那三层的花坛，一个引体向上，我就可以翻上文印室的墙，墙上没有任何铁丝等防护，从另一边直接跳下去，大约有15级楼梯高(半层楼多一点)，我已经试过，最多扭一下脚。翻过去之后，那里就有从不上锁的大门。我对学校的构造应该比任何人都熟悉。但是我要先销毁我在教室的日记。我还要在学校躲到10点之后。

我的日记现在已经销毁了，我以后再也不写这玩意了。事情在心里藏着跟写出来自己看也没什么区别。但要是写出来给别人看，我就得收着点。

那天晚上是最不寻常的。有人看过那天的云和月亮吗。从天黑开始，到刚好8点整，一分钟都不差，天上刚好飘过4个天空的云，然后一轮满月刚好完全露了出来，整个天空是带着紫色和金色的，没有树荫的地方全被照亮了。那天的云也是我没有见过的样子，是波浪的形状，刚好被风推动着。这是我无法说出来的景色。我心里突然有了一些改变，我一直认为我是在逃跑，我应该在教室学习，高考，过一个学生应有的生活。我想起我有一天晚上在音乐教室里意外地遇见了一个女生，因为上一届毕业以来再也没有人在那个时间去那种地方。我记得我只回答了她这样一句话，我没有任何的心情学习，我不是孤独，我是在逃避现实。所以我只要捡起一个爱好，就会疯狂地沉迷于其中，否则我无事可做。但那天，我意识到了做一个学生并不一定是我的生活，我完全可以把现在这样的逃跑当成我的生活。这样的生活不能说有多理想，但关于学校的情绪瞬间都消散了。我第一次明白了我不管处在什么境遇里，不管过得怎么困难，我都能活下去，我的生活是可以由我来选择的，我即使过现在这样的生活，仍然有我可以欣赏的东西，有我认为重要的东西。如果那天我没有被抓，我会很自在地收拾好书包，然后翻出学校，我没有打算要回来，我也不觉得我会生存不下去。但是莫名其妙地在当天晚上就被架回了家。开始和结尾都莫名其妙，就像个笑话一样。

只是我依然无法接受家长和老师。我不知道他们是在担心我的安全还是在批评我破坏纪律。如果是担心我的安全，我表示道歉，但其实要是我真的到了值得被担心的时候，担心我也一点用也没有。如果是因为我破坏纪律，那我不会改正，直到被处分到退学为止。现在邬小波见到我的第一句话还历历在目，“你知不知道老师找你找得很辛苦?”我知道，我还知道我躲得要辛苦地多，即便这样，我宁愿一直躲下去，你们的辛苦不在我的考虑范围之内。我这几天在网上也问了很多人，看了很多书。以前很多次跟我交流过的一个人，我认为最靠谱的一个人，回邮件跟我说，学校不一定是能教会你知识的场所，但它往往是培养一个人不错的地方。他当年是多次转学，多次读博然后又退学，然后无数次跳槽...他告诉我回学校去跟别人交往。我也许就不该问其他人，别人都会对我说这样的话。一直在家里待着是不可能的，去学校是没办法的事。但要是有一天我再次逃走了，不必来找我了，我绝对不会让我被抓到了，我那时就已经决定好了我去哪里。现在只是还有值得留恋的东西，我还没做好准备罢了。也许以后的想法会改变吧，但我为了改变这个想法已经过了两三年。也只有对未来的期待让我还能决定继续待在学校。我虽然不清楚我希望怎样的生活，但好像所有人都在跟我说:“你要优秀”，而没有人会说:“你要幸福”。